// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/session-keys/create-session-key-button.mdx?collection=docs&hash=1753855384052"
import * as docs_5 from "../content/docs/essentials/agw-provider.mdx?collection=docs&hash=1753855384052"
import * as docs_4 from "../content/docs/authentication/siwe-button.mdx?collection=docs&hash=1753855384052"
import * as docs_3 from "../content/docs/authentication/connect-wallet-button.mdx?collection=docs&hash=1753855384052"
import * as docs_2 from "../content/docs/authentication/abstract-profile.mdx?collection=docs&hash=1753855384052"
import * as docs_1 from "../content/docs/(root)/index.mdx?collection=docs&hash=1753855384052"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1753855384052"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"(root)/index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/(root)/index.mdx"}, data: docs_1 }, { info: {"path":"authentication/abstract-profile.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/abstract-profile.mdx"}, data: docs_2 }, { info: {"path":"authentication/connect-wallet-button.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/connect-wallet-button.mdx"}, data: docs_3 }, { info: {"path":"authentication/siwe-button.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/siwe-button.mdx"}, data: docs_4 }, { info: {"path":"essentials/agw-provider.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/essentials/agw-provider.mdx"}, data: docs_5 }, { info: {"path":"session-keys/create-session-key-button.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/session-keys/create-session-key-button.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/meta.json"},"data":{"pages":["(root)","essentials","authentication","session-keys"],"root":true}}, {"info":{"path":"(root)/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/(root)/meta.json"},"data":{"title":"Get Started","pages":["index"]}}, {"info":{"path":"essentials/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/essentials/meta.json"},"data":{"title":"Essentials","pages":["agw-provider"]}}, {"info":{"path":"authentication/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/meta.json"},"data":{"title":"Authentication","pages":["connect-wallet-button","siwe-button","abstract-profile"]}}, {"info":{"path":"session-keys/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/session-keys/meta.json"},"data":{"title":"Session Keys","pages":["create-session-key-button"]}}])