// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/(root)/index.mdx?collection=docs&hash=1753845077214"
import * as docs_6 from "../content/docs/components/index.mdx?collection=docs&hash=1753845077214"
import * as docs_5 from "../content/docs/components/hello-world.mdx?collection=docs&hash=1753845077214"
import * as docs_4 from "../content/docs/components/example-with-css.mdx?collection=docs&hash=1753845077214"
import * as docs_3 from "../content/docs/components/example-form.mdx?collection=docs&hash=1753845077214"
import * as docs_2 from "../content/docs/components/connect-wallet-button.mdx?collection=docs&hash=1753845077214"
import * as docs_1 from "../content/docs/components/complex-component.mdx?collection=docs&hash=1753845077214"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1753845077214"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"components/complex-component.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/components/complex-component.mdx"}, data: docs_1 }, { info: {"path":"components/connect-wallet-button.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/components/connect-wallet-button.mdx"}, data: docs_2 }, { info: {"path":"components/example-form.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/components/example-form.mdx"}, data: docs_3 }, { info: {"path":"components/example-with-css.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/components/example-with-css.mdx"}, data: docs_4 }, { info: {"path":"components/hello-world.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/components/hello-world.mdx"}, data: docs_5 }, { info: {"path":"components/index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/components/index.mdx"}, data: docs_6 }, { info: {"path":"(root)/index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/(root)/index.mdx"}, data: docs_7 }], [{"info":{"path":"meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/meta.json"},"data":{"pages":["(root)","components"],"root":true}}, {"info":{"path":"(root)/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/(root)/meta.json"},"data":{"title":"Get Started","pages":["index"]}}])