// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/docs/authentication/siwe-button.mdx?collection=docs&hash=1753855384052"
import * as docs_7 from "../content/docs/authentication/connect-wallet-button.mdx?collection=docs&hash=1753855384052"
import * as docs_6 from "../content/docs/authentication/abstract-avatar.mdx?collection=docs&hash=1753855384052"
import * as docs_5 from "../content/docs/examples/hello-world.mdx?collection=docs&hash=1753855384052"
import * as docs_4 from "../content/docs/examples/example-with-css.mdx?collection=docs&hash=1753855384052"
import * as docs_3 from "../content/docs/examples/example-form.mdx?collection=docs&hash=1753855384052"
import * as docs_2 from "../content/docs/examples/complex-component.mdx?collection=docs&hash=1753855384052"
import * as docs_1 from "../content/docs/(root)/index.mdx?collection=docs&hash=1753855384052"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1753855384052"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"(root)/index.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/(root)/index.mdx"}, data: docs_1 }, { info: {"path":"examples/complex-component.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/examples/complex-component.mdx"}, data: docs_2 }, { info: {"path":"examples/example-form.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/examples/example-form.mdx"}, data: docs_3 }, { info: {"path":"examples/example-with-css.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/examples/example-with-css.mdx"}, data: docs_4 }, { info: {"path":"examples/hello-world.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/examples/hello-world.mdx"}, data: docs_5 }, { info: {"path":"authentication/abstract-avatar.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/abstract-avatar.mdx"}, data: docs_6 }, { info: {"path":"authentication/connect-wallet-button.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/connect-wallet-button.mdx"}, data: docs_7 }, { info: {"path":"authentication/siwe-button.mdx","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/siwe-button.mdx"}, data: docs_8 }], [{"info":{"path":"meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/meta.json"},"data":{"pages":["(root)","authentication","examples"],"root":true}}, {"info":{"path":"(root)/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/(root)/meta.json"},"data":{"title":"Get Started","pages":["index"]}}, {"info":{"path":"authentication/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/authentication/meta.json"},"data":{"title":"Authentication","pages":["connect-wallet-button","siwe-button","abstract-avatar"]}}, {"info":{"path":"examples/meta.json","absolutePath":"/Users/jarrod/agw-reusables/content/docs/examples/meta.json"},"data":{"title":"Examples","pages":["hello-world","example-form","example-with-css","complex-component"]}}])